__all__ = [ 'ccmap',
            'gcmap',
            'importer',
            'ccmapHelpers',
            'cmstats',
            'normalizer',
            'normalizeKnightRuiz',
            'genomicsDataHandler',
            'corrMatrix',
            'statDist']
